# Generated by Django 5.0.1 on 2024-02-22 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Account number must be exactly 4 digits')])),
                ('name', models.CharField(max_length=255)),
                ('default_accounting_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEnteryLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounting_date', models.DateField()),
                ('account', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('reconciled', models.BooleanField(default=False)),
                ('currency', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('accounting_type', models.CharField(max_length=255)),
            ],
        ),
    ]
