# Generated by Django 5.0.1 on 2024-02-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_account_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalenterylines',
            name='account',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
